/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./components/Home.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowErrorNormal: typeof import('./components/Vuelidate/ShowErrorNormal.vue')['default']
    ShowErrorVuelidate: typeof import('./components/Vuelidate/ShowErrorVuelidate.vue')['default']
  }
}
